export const metadata = {
  title: "Add Product | Next-Hero",
  description: "Generated by create next app",
};

const addProduct = () => {
  return <div>Add Product</div>;
};

export default addProduct;
