export const metadata = {
  title: "Manage Product | Next-Hero",
  description: "Generated by create next app",
};

const manageProduct = () => {
  return <div>manage Product</div>;
};

export default manageProduct;
