export const metadata = {
  title: "single Blog | Next-Hero",
  description: "Generated by create next app",
};

const SingleBlog = () => {
  return <div>singleBlog</div>;
};

export default SingleBlog;
