// "use client";
// import { useParams, useSearchParams } from "next/navigation";

import loadBlogData from "@/utils/loadBlogData";
import loadSingleBlogData from "@/utils/loadSingleBlogData";

// export const metadata = {
//   title: "single Blog | Next-Hero",
//   description: "Generated by create next app",
// };

export const generateMetadata = async ({ params }) => {
  const { title } = await loadSingleBlogData(params.id);
  return {
    title: title,
  };
};

export const generateStaticParams = async () => {
  const blogs = await loadBlogData();
  return blogs.map(({ id }) => {
    id: id.toString();
  });
};

const SingleBlog = async ({ params }) => {
  // const [year, id] = params.segment;
  // const params2 = useParams();
  // const search = useSearchParams();
  // console.log(params2.segment, search.get("title"));

  const { id, body, title } = await loadSingleBlogData(params.id);
  return (
    <div className="border border-blue-900 my-2 p-2 mx-10">
      <h2 className="text-2xl">
        {id}. {title}
      </h2>
      <p>{body}</p>
    </div>
  );
};

export default SingleBlog;
