import Link from "next/link";
export const metadata = {
  title: "404 | Next-Hero",
  description: "Generated by create next app",
};

const NotFountPage = () => {
  return (
    <div className="text-center mt-20">
      <h1 className="text-4xl font-bold">404</h1>
      <Link href="/" className="btn bg-red-400 p-4 mt-5 rounded">
        back to Home
      </Link>
    </div>
  );
};

export default NotFountPage;
