import Categories from "@/components/Categories";

export const metadata = {
  title: "Home | Next-Hero",
  description: "Generated by create next app",
};

// import img1 from "@/assets/pic-1.jpg";
// import img2 from "@/assets/pic-2.jpg";
// import Image from "next/image";

const HomePage = () => {
  return (
    <main>
      <h1>Home</h1>
      {/* <Image
        src="https://media.istockphoto.com/id/1442179368/photo/maldives-island.webp?b=1&s=170667a&w=0&k=20&c=i8wK-BoIq_B365rf0oMRBNmuMc4U1zlTUllMuyr_QNw="
        width={600}
        height={382}
        alt=""
      /> */}
      <Categories></Categories>
    </main>
  );
};
export default HomePage;
