export const metadata = {
  title: "Dashboard | Next-Hero",
  description: "Generated by create next app",
};

const DashboardPage = () => {
  return <div>dashboard</div>;
};

export default DashboardPage;
